"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const cp = require("node:child_process");
const snapshot = require("../research/reports/project-state-audit.json");

const read = file => fs.readFileSync(path.join(__dirname, "..", file), "utf8");
const git = (...args) => cp.execFileSync("git", args, { cwd: path.join(__dirname, ".."), encoding: "utf8" }).trim();

test("project-state snapshot contains executable audit invariants", () => {
  assert.equal(snapshot.snapshotBasis, "post-triumph-streettriple765-prospect-registration-working-tree");
  assert.equal(snapshot.snapshotImplementationPath, "research/data/triumph-streettriple765-prospect-registration.js");
  const containingCommit = git("log", "-1", "--format=%H", "--", snapshot.snapshotImplementationPath);
  const expectedBase = containingCommit ? git("rev-parse", `${containingCommit}^`) : git("rev-parse", "HEAD");
  assert.equal(snapshot.baseCommit, expectedBase);
  assert.equal(snapshot.commitsFromBaseThroughContaining, 1);
  assert.equal(Object.prototype.hasOwnProperty.call(snapshot, "containingCommit"), false);
  assert.equal(Object.prototype.hasOwnProperty.call(snapshot, "aheadAfterContainingCommit"), false);
  assert.equal(Object.prototype.hasOwnProperty.call(snapshot, "originMain"), false);
  assert.equal(Object.prototype.hasOwnProperty.call(snapshot, "behind"), false);
  assert.equal(snapshot.catalogue.manufacturers, 13);
  assert.equal(snapshot.catalogue.variants, 1095);
  assert.equal(snapshot.catalogue.contentCompleteness, "incomplete");
  assert.equal(snapshot.catalogue.latestCompletedExpansion, "Triumph Wave 2");
  assert.equal(snapshot.research.serviceCoreFieldCount, 44);
  assert.equal(snapshot.research.hondaServiceWave1.targets, 8);
  assert.equal(snapshot.research.batchWave2.selectedTargets, 12);
  assert.equal(snapshot.research.batchWave2.targetFieldSlots, 528);
  assert.equal(snapshot.research.batchWave2.netNewVerifiedSlots, 6);
  assert.equal(snapshot.research.highValuePilot.selectedTargets, 5);
  assert.equal(snapshot.research.highValuePilot.minimumPracticalServiceFields, 10);
  assert.equal(snapshot.research.highValuePilot.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.highValuePilot.serviceCoreBefore, 51);
  assert.equal(snapshot.research.highValuePilot.serviceCoreAfter, 101);
  assert.equal(snapshot.research.highValuePilot.practicalServiceFieldGain, 48);
  assert.equal(snapshot.research.postPilotScalingReassessment.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.postPilotScalingReassessment.candidatePool, 10);
  assert.equal(snapshot.research.postPilotScalingReassessment.manufacturersEvaluated, 7);
  assert.deepEqual(snapshot.research.postPilotScalingReassessment.selectedTargets.map(target => target.catalogVariantKey), ["yamaha.mt-09.gen3", "yamaha.tenere-700.gen1"]);
  assert.equal(snapshot.research.yamahaTransferAcquisition.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.yamahaTransferAcquisition.netNewVerifiedSlots, 58);
  assert.equal(snapshot.research.yamahaTransferAcquisition.practicalServiceFieldGain, 54);
  assert.equal(snapshot.research.yamahaTransferAcquisition.conflictsDiscovered, 0);
  assert.equal(snapshot.research.postYamahaTransferDesign.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.postYamahaTransferDesign.candidatePool, 10);
  assert.equal(snapshot.research.postYamahaTransferDesign.manufacturersEvaluated, 8);
  assert.equal(snapshot.research.postYamahaTransferDesign.unknownUnranked, 5);
  assert.deepEqual(snapshot.research.postYamahaTransferDesign.selectedTargets.map(target => target.catalogVariantKey), ["harley-davidson.revolution-max.sportster-s"]);
  assert.equal(snapshot.research.postYamahaTransferDesign.evidenceAcquired, false);
  assert.equal(snapshot.research.harleyTransferAcquisition.classification, "REJECT");
  assert.equal(snapshot.research.harleyTransferAcquisition.source.publicationId, "94001064");
  assert.equal(snapshot.research.harleyTransferAcquisition.source.publicationDate, 2023);
  assert.equal(snapshot.research.harleyTransferAcquisition.metrics.verifiedSlotsBefore, 0);
  assert.equal(snapshot.research.harleyTransferAcquisition.metrics.verifiedSlotsAfter, 0);
  assert.equal(snapshot.research.harleyTransferAcquisition.metrics.practicalGain, 0);
  assert.equal(snapshot.research.harleyTransferAcquisition.thresholdResult.allPassed, false);
  assert.equal(snapshot.research.postYamahaTransferDesign.historicalStatus, "SUPERSEDED-BY-EXECUTION");
  assert.equal(snapshot.research.postYamahaTransferDesign.currentHarleyProspectClassification, "REJECTED-MISMATCH");
  assert.equal(snapshot.research.sourceProspectReadiness.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.sourceProspectReadiness.inventory, 18);
  assert.equal(snapshot.research.sourceProspectReadiness.manufacturers, 8);
  assert.equal(snapshot.research.sourceProspectReadiness.executionReady, 1);
  assert.equal(snapshot.research.sourceProspectReadiness.thirdManufacturerAnswer, "NO");
  assert.equal(snapshot.research.sourceProspectReadiness.serviceCoreCoverageChanged, false);
  assert.equal(snapshot.ducatiMonster937Registration.classification, "EXECUTION-READY");
  assert.equal(snapshot.ducatiMonster937Registration.sourceTier, "A");
  assert.equal(snapshot.ducatiMonster937Registration.documentClass, "owner manual");
  assert.equal(snapshot.ducatiMonster937Registration.readiness.passed, true);
  assert.equal(snapshot.ducatiMonster937Registration.technicalValuesInspected, false);
  assert.equal(snapshot.ducatiMonster937Registration.serviceCoreCoverageChanged, false);
  assert.equal(snapshot.ducatiMonster937Acquisition.rawCandidates, 27);
  assert.equal(snapshot.ducatiMonster937Acquisition.reviewDecisionCounts.queued, 27);
  assert.equal(snapshot.ducatiMonster937Acquisition.evidenceRowsCreated, 0);
  assert.equal(snapshot.ducatiMonster937Acquisition.serviceCoreBefore, 0);
  assert.equal(snapshot.ducatiMonster937Acquisition.serviceCoreAfter, 0);
  assert.equal(snapshot.ducatiMonster937Acquisition.practicalGain, 0);
  assert.equal(snapshot.ducatiMonster937Acquisition.conflicts, 0);
  assert.equal(snapshot.ducatiMonster937Acquisition.ambiguousFields, 0);
  assert.equal(snapshot.ducatiMonster937Acquisition.productionChanged, false);
  assert.equal(snapshot.ducatiMonster937HumanReview.candidatesReviewed, 27);
  assert.deepEqual(snapshot.ducatiMonster937HumanReview.decisionCounts, { ACCEPT: 27, REJECT: 0, "NEEDS-MORE-REVIEW": 0 });
  assert.equal(snapshot.ducatiMonster937HumanReview.unresolvedOrAmbiguous, 0);
  assert.equal(snapshot.ducatiMonster937HumanReview.rawValuesAndProvenanceUnchanged, true);
  assert.equal(snapshot.ducatiMonster937HumanReview.evidenceRowsCreated, 0);
  assert.equal(snapshot.ducatiMonster937HumanReview.serviceCoreCoverageChange, 0);
  assert.equal(snapshot.ducatiMonster937HumanReview.productionChanged, false);
  assert.equal(snapshot.ducatiMonster937EvidenceProcessing.processingRecords, 27);
  assert.equal(snapshot.ducatiMonster937EvidenceProcessing.acceptedForProcessing, 27);
  assert.equal(snapshot.ducatiMonster937EvidenceProcessing.cannotAdvance, 0);
  assert.equal(snapshot.ducatiMonster937EvidenceProcessing.rejectedCandidate, 0);
  assert.equal(snapshot.ducatiMonster937EvidenceProcessing.needsMoreReview, 0);
  assert.equal(snapshot.ducatiMonster937EvidenceProcessing.ineligible, 0);
  assert.equal(snapshot.ducatiMonster937EvidenceProcessing.conflictsDetected, 0);
  assert.equal(snapshot.ducatiMonster937EvidenceProcessing.rawValuesAndProvenancePreserved, true);
  assert.equal(snapshot.ducatiMonster937EvidenceProcessing.evidenceRowsCreated, 0);
  assert.equal(snapshot.ducatiMonster937EvidenceProcessing.productionChanged, false);
  assert.equal(snapshot.kawasakiNinja650Registration.classification, "ACCESS-BLOCKED");
  assert.equal(snapshot.kawasakiNinja650Registration.target.catalogVariantKey, "kawasaki.ninja-650.gen2");
  assert.equal(snapshot.kawasakiNinja650Registration.target.scope.years.from, 2020);
  assert.equal(snapshot.kawasakiNinja650Registration.sourceTier, "A");
  assert.equal(snapshot.kawasakiNinja650Registration.documentClass, "owner manual");
  assert.equal(snapshot.kawasakiNinja650Registration.readiness.passed, false);
  assert.equal(snapshot.kawasakiNinja650Registration.technicalValuesInspected, false);
  assert.equal(snapshot.kawasakiNinja650Registration.evidenceRowsAdded, 0);
  assert.equal(snapshot.kawasakiNinja650Registration.serviceCoreCoverageChanged, false);
  assert.equal(snapshot.kawasakiNinja650Registration.productionChanged, false);
  assert.equal(snapshot.bmwF900RRegistration.classification, "EXECUTION-READY");
  assert.equal(snapshot.bmwF900RRegistration.target.catalogVariantKey, "bmw.f-roadster-xr.f900r-1");
  assert.equal(snapshot.bmwF900RRegistration.target.scope.years.from, 2020);
  assert.equal(snapshot.bmwF900RRegistration.sourceTier, "A");
  assert.equal(snapshot.bmwF900RRegistration.documentClass, "rider manual");
  assert.equal(snapshot.bmwF900RRegistration.readiness.passed, true);
  assert.equal(snapshot.bmwF900RRegistration.technicalValuesInspected, false);
  assert.equal(snapshot.bmwF900RRegistration.evidenceRowsAdded, 0);
  assert.equal(snapshot.bmwF900RRegistration.serviceCoreCoverageChanged, false);
  assert.equal(snapshot.bmwF900RRegistration.productionChanged, false);
  assert.equal(snapshot.bmwF900RAcquisition.source.publicationId, "F_0K11_RM_0520_76.pdf");
  assert.equal(snapshot.bmwF900RAcquisition.target.catalogVariantKey, "bmw.f-roadster-xr.f900r-1");
  assert.equal(snapshot.bmwF900RAcquisition.rawCandidates, snapshot.bmwF900RAcquisition.queuedCandidates);
  assert.ok(snapshot.bmwF900RAcquisition.rawCandidates > 0);
  assert.equal(snapshot.bmwF900RAcquisition.ambiguousCandidates, 0);
  assert.equal(snapshot.bmwF900RAcquisition.conflictingCandidates, 0);
  assert.equal(snapshot.bmwF900RAcquisition.technicalValuesInspected, true);
  assert.equal(snapshot.bmwF900RAcquisition.evidenceRowsCreated, 0);
  assert.equal(snapshot.bmwF900RAcquisition.serviceCoreBefore, 0);
  assert.equal(snapshot.bmwF900RAcquisition.serviceCoreAfter, 0);
  assert.equal(snapshot.bmwF900RAcquisition.productionChanged, false);
  assert.equal(snapshot.bmwF900RHumanReview.candidatesReviewed, 13);
  assert.deepEqual(snapshot.bmwF900RHumanReview.decisionCounts, { ACCEPT: 13, REJECT: 0, "NEEDS-MORE-REVIEW": 0 });
  assert.equal(snapshot.bmwF900RHumanReview.unresolvedOrAmbiguous, 0);
  assert.equal(snapshot.bmwF900RHumanReview.rawValuesAndProvenanceUnchanged, true);
  assert.equal(snapshot.bmwF900RHumanReview.evidenceRowsCreated, 0);
  assert.equal(snapshot.bmwF900RHumanReview.serviceCoreBefore, 0);
  assert.equal(snapshot.bmwF900RHumanReview.serviceCoreAfter, 0);
  assert.equal(snapshot.bmwF900RHumanReview.productionChanged, false);
  assert.equal(snapshot.bmwF900REvidenceProcessing.target.catalogVariantKey, "bmw.f-roadster-xr.f900r-1");
  assert.equal(snapshot.bmwF900REvidenceProcessing.source.publicationId, "F_0K11_RM_0520_76.pdf");
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.processingRecords, 13);
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.acceptedForProcessing, 11);
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.cannotAdvance, 2);
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.rejectedCandidate, 0);
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.needsMoreReview, 0);
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.ineligible, 0);
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.conflictsDetected, 2);
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.rawValuesAndProvenancePreserved, true);
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.humanReviewDecisionsUnchanged, true);
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.evidenceRowsCreated, 0);
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.serviceCoreBefore, 0);
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.serviceCoreAfter, 0);
  assert.equal(snapshot.bmwF900REvidenceProcessing.metrics.productionChanged, false);
  assert.equal(snapshot.triumphStreetTriple765Registration.classification, "AUTHENTICATED-BUT-APPLICABILITY-PARTIAL");
  assert.equal(snapshot.triumphStreetTriple765Registration.target.catalogVariantKey, "triumph.street-triple.765-3");
  assert.equal(snapshot.triumphStreetTriple765Registration.target.scope.years.from, 2023);
  assert.equal(snapshot.triumphStreetTriple765Registration.sourceTier, "A");
  assert.equal(snapshot.triumphStreetTriple765Registration.documentClass, "owner handbook");
  assert.equal(snapshot.triumphStreetTriple765Registration.readiness.passed, false);
  assert.equal(snapshot.triumphStreetTriple765Registration.technicalValuesInspected, false);
  assert.equal(snapshot.triumphStreetTriple765Registration.evidenceRowsAdded, 0);
  assert.equal(snapshot.triumphStreetTriple765Registration.serviceCoreCoverageChanged, false);
  assert.equal(snapshot.triumphStreetTriple765Registration.productionChanged, false);
  assert.equal(snapshot.postBmwTriumphPhase5Reassessment.candidatesReassessed, 18);
  assert.equal(snapshot.postBmwTriumphPhase5Reassessment.viableCandidatesRemaining.length, 0);
  assert.equal(snapshot.postBmwTriumphPhase5Reassessment.selectedNextTarget, null);
  assert.equal(snapshot.postBmwTriumphPhase5Reassessment.newExternalResearchPerformed, false);
  assert.equal(snapshot.postBmwTriumphPhase5Reassessment.technicalValuesInspected, false);
  assert.equal(snapshot.postBmwTriumphPhase5Reassessment.evidenceRowsAdded, 0);
  assert.equal(snapshot.postBmwTriumphPhase5Reassessment.serviceCoreCoverageChanged, false);
  assert.equal(snapshot.postBmwTriumphPhase5Reassessment.productionChanged, false);
  assert.deepEqual(snapshot.promotionFoundation, { contract: "PromotionPacket/v1", gate: "PROMOTION-READY-or-BLOCKED", positiveFixture: "synthetic-only", productionConversion: false, registryInsertion: false, evidenceRowsCreated: false, rawNormalization: false, realResearchRecordsConsumed: false, gateExported: true });
  assert.deepEqual(snapshot.heldPromotionProjection.ducati, { total: 27, promotionReady: 27, blocked: 0 });
  assert.deepEqual(snapshot.heldPromotionProjection.bmw, { total: 13, promotionReady: 11, blocked: 2, blockedReasons: { noUnresolvedConflict: 2, processingAccepted: 2 } });
  assert.equal(snapshot.heldPromotionProjection.upstreamResearchStateChanged, false);
  assert.equal(snapshot.heldPromotionProjection.productionStateChanged, false);
  assert.equal(snapshot.heldPromotionProjection.evidenceRowsCreated, 0);
  assert.equal(snapshot.heldPromotionProjection.serviceCoreCoverageChanged, false);
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.classification, "ACCESS-BLOCKED");
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.audit, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.b7nLitRelationship, "UNRESOLVED");
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.readinessPassed, false);
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.evidenceRowsAdded, 0);
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.serviceCoreCoverageChanged, false);
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.historicalStatus, "FOLLOWED-BY-RECONCILIATION");
  assert.equal(snapshot.research.mt09PublicationReconciliation.relationship, "RELATIONSHIP-UNRESOLVED");
  assert.equal(snapshot.research.mt09PublicationReconciliation.classification, "ACCESS-BLOCKED");
  assert.equal(snapshot.research.mt09PublicationReconciliation.antiLoop, "MT09-AUTHENTICATION-PATH-EXHAUSTED");
  assert.equal(snapshot.research.mt09PublicationReconciliation.audit, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.mt09PublicationReconciliation.readinessPassed, false);
  assert.equal(snapshot.research.mt09PublicationReconciliation.evidenceRowsAdded, 0);
  assert.equal(snapshot.research.mt09PublicationReconciliation.researchedNoEvidenceAdded, 0);
  assert.equal(snapshot.research.mt09PublicationReconciliation.serviceCoreCoverageChanged, false);
  assert.equal(snapshot.research.vfr800.verified, 13);
  assert.equal(snapshot.research.cbr500r.verified, 26);
  assert.equal(snapshot.productionBoundary.researchImportedByIndex, false);
  assert.equal(snapshot.productionBoundary.batchPipelineNonProduction, true);
  assert.equal(snapshot.technicalResearchFactory.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.technicalResearchFactory.exactNextTasks.length, 1);
  assert.equal(snapshot.technicalResearchFactory.tenerePilot.role, "FACTORY-PILOT-CANDIDATE");
  assert.equal(snapshot.technicalResearchFactory.evidenceAdded, false);
  assert.equal(snapshot.technicalResearchFactory.serviceCoreChanged, false);
  assert.equal(snapshot.technicalResearchFactory.productionChanged, false);
  assert.equal(snapshot.factoryFoundation.contractVersion, 1);
  assert.equal(snapshot.factoryFoundation.classification, "ACCEPT-WITH-RISKS");
  assert.deepEqual(snapshot.factoryFoundation.contracts, ["ResearchTarget", "SourceProspect", "ApplicabilityScope", "GapPlan"]);
  assert.equal(snapshot.factoryFoundation.fixtures.length, 5);
  assert.equal(snapshot.factoryFoundation.serviceCoreFieldCount, 44);
  assert.equal(snapshot.factoryFoundation.tenerePilot.authenticated, false);
  assert.equal(snapshot.factoryFoundation.exactNextTasks.length, 1);
  assert.equal(snapshot.factoryFoundation.evidenceAdded, false);
  assert.equal(snapshot.factoryFoundation.coverageChanged, false);
  assert.equal(snapshot.orchestratorFoundation.schemaVersion, 1);
  assert.equal(snapshot.orchestratorFoundation.foundationContractVersion, 1);
  assert.equal(snapshot.orchestratorFoundation.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.orchestratorFoundation.contracts.length, 7);
  assert.equal(snapshot.orchestratorFoundation.eventTypes.length, 13);
  assert.equal(snapshot.orchestratorFoundation.fixtures.length, 4);
  assert.ok(snapshot.orchestratorFoundation.fixtures.every(item => item.replayVerified));
  assert.equal(snapshot.orchestratorFoundation.serviceCoreFieldCount, 44);
  assert.equal(snapshot.orchestratorFoundation.exactNextTasks.length, 1);
  assert.equal(snapshot.orchestratorFoundation.evidenceAdded, false);
  assert.equal(snapshot.orchestratorFoundation.productionChanged, false);
  assert.equal(snapshot.orchestratorFoundation.tenereAuthenticationExecuted, false);
  assert.equal(snapshot.executionPlanner.schemaVersion, 1);
  assert.equal(snapshot.executionPlanner.foundationContractVersion, 1);
  assert.equal(snapshot.executionPlanner.orchestratorSchemaVersion, 1);
  assert.equal(snapshot.executionPlanner.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.executionPlanner.summary.batchesProduced, 1);
  assert.equal(snapshot.executionPlanner.summary.workItemsProduced, 1);
  assert.deepEqual(snapshot.executionPlanner.summary.decisionCounts, { BLOCKED: 1, DEFERRED: 4, "NOT-NEEDED": 1, PLANNED: 1, REJECTED: 1 });
  assert.equal(snapshot.executionPlanner.fixtureResults["tenere-service"].decision, "BLOCKED");
  assert.equal(snapshot.executionPlanner.serviceCoreFieldCount, 44);
  assert.equal(snapshot.executionPlanner.exactNextTasks.length, 1);
  assert.equal(snapshot.executionPlanner.evidenceAdded, false);
  assert.equal(snapshot.executionPlanner.productionChanged, false);
  assert.equal(snapshot.executionPlanner.tenereAuthenticationExecuted, false);
  assert.equal(snapshot.executionAgent.schemaVersion, 1);
  assert.equal(snapshot.executionAgent.orchestratorSchemaVersion, 1);
  assert.equal(snapshot.executionAgent.adapterSchemaVersion, 1);
  assert.equal(snapshot.executionAgent.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.executionAgent.adapters.length, 10);
  assert.equal(snapshot.executionAgent.serviceCoreFieldCount, 44);
  assert.equal(snapshot.executionAgent.evidenceAdded, false);
  assert.equal(snapshot.executionAgent.researchedNoEvidenceAdded, false);
  assert.equal(snapshot.executionAgent.productionChanged, false);
  assert.equal(snapshot.executionAgent.tenereAuthenticationExecuted, false);
  assert.equal(snapshot.extractionAgent.schemaVersion, 1);
  assert.equal(snapshot.extractionAgent.executionSchemaVersion, 1);
  assert.equal(snapshot.extractionAgent.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.extractionAgent.adapters.length, 7);
  assert.equal(snapshot.extractionAgent.dispositions.length, 8);
  assert.equal(snapshot.extractionAgent.examples.candidates, "CANDIDATES-PRODUCED");
  assert.equal(snapshot.extractionAgent.provenance.batchViaTargetWork, true);
  assert.equal(snapshot.extractionAgent.provenance.sourceWorkHasNoBatchId, true);
  assert.equal(snapshot.extractionAgent.safety.rawOnly, true);
  assert.equal(snapshot.extractionAgent.safety.reviewQueueStarted, false);
  assert.equal(snapshot.extractionAgent.safety.productionChanged, false);
  assert.equal(snapshot.reviewQueue.schemaVersion, 1);
  assert.equal(snapshot.reviewQueue.extractionSchemaVersion, 1);
  assert.equal(snapshot.reviewQueue.classification, "ACCEPT-WITH-RISKS");
  assert.deepEqual(snapshot.reviewQueue.queueStates, ["QUEUED"]);
  assert.deepEqual(snapshot.reviewQueue.eligibilityStates, ["ELIGIBLE", "NOT-ELIGIBLE"]);
  assert.equal(snapshot.reviewQueue.entryCount, 2);
  assert.equal(snapshot.reviewQueue.exactDuplicateCollapsed, true);
  assert.equal(snapshot.reviewQueue.provenance.resultBound, true);
  assert.equal(snapshot.reviewQueue.provenance.candidateBound, true);
  assert.equal(snapshot.reviewQueue.rawPreservation.normalized, false);
  assert.equal(snapshot.reviewQueue.safety.humanDecisionsImplemented, false);
  assert.equal(snapshot.reviewQueue.safety.researchedNoEvidenceAdded, false);
  assert.equal(snapshot.reviewQueue.safety.persistenceImplemented, false);
  assert.equal(snapshot.reviewQueue.safety.orchestratorEventsAdded, 0);
  assert.equal(snapshot.reviewQueue.safety.productionChanged, false);
  assert.equal(snapshot.humanReviewDecisions.schemaVersion, 1);
  assert.equal(snapshot.humanReviewDecisions.reviewQueueSchemaVersion, 1);
  assert.equal(snapshot.humanReviewDecisions.classification, "ACCEPT-WITH-RISKS");
  assert.deepEqual(snapshot.humanReviewDecisions.decisionVocabulary, ["ACCEPT", "REJECT", "NEEDS-MORE-REVIEW"]);
  assert.equal(snapshot.humanReviewDecisions.examples.ACCEPT, "ACCEPT");
  assert.equal(snapshot.humanReviewDecisions.decisionCount, 2);
  assert.equal(snapshot.humanReviewDecisions.provenance.queueEntryBound, true);
  assert.equal(snapshot.humanReviewDecisions.provenance.candidateBound, true);
  assert.equal(snapshot.humanReviewDecisions.semantics.acceptMeansProceedToFutureProcessingOnly, true);
  assert.equal(snapshot.humanReviewDecisions.semantics.needsMoreReviewTriggersNoAutomation, true);
  assert.equal(snapshot.humanReviewDecisions.safety.evidenceAdded, false);
  assert.equal(snapshot.humanReviewDecisions.safety.researchedNoEvidenceAdded, false);
  assert.equal(snapshot.humanReviewDecisions.safety.normalizationImplemented, false);
  assert.equal(snapshot.humanReviewDecisions.safety.conflictResolutionImplemented, false);
  assert.equal(snapshot.humanReviewDecisions.safety.persistenceImplemented, false);
  assert.equal(snapshot.humanReviewDecisions.safety.orchestratorEventsAdded, 0);
  assert.equal(snapshot.humanReviewDecisions.safety.productionChanged, false);
});

test("project-state report regenerates byte-for-byte from its semantic snapshot convention", () => {
  const generated = cp.execFileSync(process.execPath, [path.join(__dirname, "../scripts/project-state-audit.js")]);
  assert.deepEqual(generated, fs.readFileSync(path.join(__dirname, "../research/reports/project-state-audit.json")));
});

test("project memory has one active roadmap phase and unique ADRs", () => {
  const roadmap = read("docs/project/ROADMAP.md");
  assert.equal((roadmap.match(/\(ACTIVE\)/g) || []).length, 1);
  const decisions = read("docs/project/DECISIONS.md");
  const ids = [...decisions.matchAll(/## (ADR-\d+)/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length);
  const state = read("docs/project/CURRENT_STATE.md");
  assert.equal((state.match(/\*\*NEXT\*\*/g) || []).length, 1);
  assert.match(state, /Technical Research Factory Human Review Decisions Foundation/);
});

test("project memory records production/research isolation", () => {
  assert.match(read("docs/project/README.md"), /Authority order/);
  assert.match(read("docs/project/chat-archive/README.md"), /NON-AUTHORITATIVE HISTORICAL CONTEXT/);
  assert.match(read("docs/project/CURRENT_STATE.md"), /Research is quarantined/);
  assert.doesNotMatch(read("index.html"), /research\/data|research\/lib/);
});

test("audit standard and batch metrics prevent circular acceptance", () => {
  const standard = read("docs/project/AUDIT_STANDARD.md");
  assert.match(standard, /IMPLEMENT → AUTHOR TESTS → INDEPENDENT AUDIT/);
  assert.match(standard, /JUSTIFIED-WITH-RISK/);
  assert.match(standard, /ACCEPT-WITH-RISKS/);
  assert.match(standard, /attempts to falsify/);
  assert.equal(snapshot.research.batchWave2.practicalServiceFieldGain, 0);
  assert.equal(snapshot.research.batchWave2.verifiedBefore, 51);
  assert.equal(snapshot.research.batchWave2.verifiedAfter, 57);
});

test("project memory records the executed pilot and operator cloud note", () => {
  const state = read("docs/project/CURRENT_STATE.md");
  assert.match(state, /\*\*NEXT\*\*/);
  assert.match(read("docs/project/WORKLOG.md"), /high-value source-acquisition/);
  assert.match(state, /101\/220/);
  assert.match(state, /FACTORY-PILOT-CANDIDATE/);
  assert.match(read("docs/project/DECISIONS.md"), /ADR-010/);
  assert.match(read("docs/project/DECISIONS.md"), /ADR-011/);
  assert.match(read("docs/project/DECISIONS.md"), /ADR-013/);
});
