"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const snapshot = require("../research/reports/project-state-audit.json");

const read = file => fs.readFileSync(path.join(__dirname, "..", file), "utf8");

test("project-state snapshot contains executable audit invariants", () => {
  assert.equal(snapshot.snapshotBasis, "post-technical-research-factory-execution-agent-working-tree");
  assert.match(snapshot.baseCommit, /^[0-9a-f]{40}$/);
  assert.equal(snapshot.aheadAfterContainingCommit, 12);
  assert.match(snapshot.originMain, /^[0-9a-f]{40}$/);
  assert.equal(snapshot.catalogue.manufacturers, 13);
  assert.equal(snapshot.catalogue.variants, 1095);
  assert.equal(snapshot.catalogue.contentCompleteness, "incomplete");
  assert.equal(snapshot.catalogue.latestCompletedExpansion, "Triumph Wave 2");
  assert.equal(snapshot.research.serviceCoreFieldCount, 44);
  assert.equal(snapshot.research.hondaServiceWave1.targets, 8);
  assert.equal(snapshot.research.batchWave2.selectedTargets, 12);
  assert.equal(snapshot.research.batchWave2.targetFieldSlots, 528);
  assert.equal(snapshot.research.batchWave2.netNewVerifiedSlots, 6);
  assert.equal(snapshot.research.highValuePilot.selectedTargets, 5);
  assert.equal(snapshot.research.highValuePilot.minimumPracticalServiceFields, 10);
  assert.equal(snapshot.research.highValuePilot.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.highValuePilot.serviceCoreBefore, 51);
  assert.equal(snapshot.research.highValuePilot.serviceCoreAfter, 101);
  assert.equal(snapshot.research.highValuePilot.practicalServiceFieldGain, 48);
  assert.equal(snapshot.research.postPilotScalingReassessment.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.postPilotScalingReassessment.candidatePool, 10);
  assert.equal(snapshot.research.postPilotScalingReassessment.manufacturersEvaluated, 7);
  assert.deepEqual(snapshot.research.postPilotScalingReassessment.selectedTargets.map(target => target.catalogVariantKey), ["yamaha.mt-09.gen3", "yamaha.tenere-700.gen1"]);
  assert.equal(snapshot.research.yamahaTransferAcquisition.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.yamahaTransferAcquisition.netNewVerifiedSlots, 58);
  assert.equal(snapshot.research.yamahaTransferAcquisition.practicalServiceFieldGain, 54);
  assert.equal(snapshot.research.yamahaTransferAcquisition.conflictsDiscovered, 0);
  assert.equal(snapshot.research.postYamahaTransferDesign.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.postYamahaTransferDesign.candidatePool, 10);
  assert.equal(snapshot.research.postYamahaTransferDesign.manufacturersEvaluated, 8);
  assert.equal(snapshot.research.postYamahaTransferDesign.unknownUnranked, 5);
  assert.deepEqual(snapshot.research.postYamahaTransferDesign.selectedTargets.map(target => target.catalogVariantKey), ["harley-davidson.revolution-max.sportster-s"]);
  assert.equal(snapshot.research.postYamahaTransferDesign.evidenceAcquired, false);
  assert.equal(snapshot.research.harleyTransferAcquisition.classification, "REJECT");
  assert.equal(snapshot.research.harleyTransferAcquisition.source.publicationId, "94001064");
  assert.equal(snapshot.research.harleyTransferAcquisition.source.publicationDate, 2023);
  assert.equal(snapshot.research.harleyTransferAcquisition.metrics.verifiedSlotsBefore, 0);
  assert.equal(snapshot.research.harleyTransferAcquisition.metrics.verifiedSlotsAfter, 0);
  assert.equal(snapshot.research.harleyTransferAcquisition.metrics.practicalGain, 0);
  assert.equal(snapshot.research.harleyTransferAcquisition.thresholdResult.allPassed, false);
  assert.equal(snapshot.research.postYamahaTransferDesign.historicalStatus, "SUPERSEDED-BY-EXECUTION");
  assert.equal(snapshot.research.postYamahaTransferDesign.currentHarleyProspectClassification, "REJECTED-MISMATCH");
  assert.equal(snapshot.research.sourceProspectReadiness.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.sourceProspectReadiness.inventory, 17);
  assert.equal(snapshot.research.sourceProspectReadiness.manufacturers, 8);
  assert.equal(snapshot.research.sourceProspectReadiness.executionReady, 0);
  assert.equal(snapshot.research.sourceProspectReadiness.thirdManufacturerAnswer, "NO");
  assert.equal(snapshot.research.sourceProspectReadiness.serviceCoreCoverageChanged, false);
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.classification, "ACCESS-BLOCKED");
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.audit, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.b7nLitRelationship, "UNRESOLVED");
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.readinessPassed, false);
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.evidenceRowsAdded, 0);
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.serviceCoreCoverageChanged, false);
  assert.equal(snapshot.research.mt09ServiceProspectAuthentication.historicalStatus, "FOLLOWED-BY-RECONCILIATION");
  assert.equal(snapshot.research.mt09PublicationReconciliation.relationship, "RELATIONSHIP-UNRESOLVED");
  assert.equal(snapshot.research.mt09PublicationReconciliation.classification, "ACCESS-BLOCKED");
  assert.equal(snapshot.research.mt09PublicationReconciliation.antiLoop, "MT09-AUTHENTICATION-PATH-EXHAUSTED");
  assert.equal(snapshot.research.mt09PublicationReconciliation.audit, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.research.mt09PublicationReconciliation.readinessPassed, false);
  assert.equal(snapshot.research.mt09PublicationReconciliation.evidenceRowsAdded, 0);
  assert.equal(snapshot.research.mt09PublicationReconciliation.researchedNoEvidenceAdded, 0);
  assert.equal(snapshot.research.mt09PublicationReconciliation.serviceCoreCoverageChanged, false);
  assert.equal(snapshot.research.vfr800.verified, 13);
  assert.equal(snapshot.research.cbr500r.verified, 26);
  assert.equal(snapshot.productionBoundary.researchImportedByIndex, false);
  assert.equal(snapshot.productionBoundary.batchPipelineNonProduction, true);
  assert.equal(snapshot.technicalResearchFactory.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.technicalResearchFactory.exactNextTasks.length, 1);
  assert.equal(snapshot.technicalResearchFactory.tenerePilot.role, "FACTORY-PILOT-CANDIDATE");
  assert.equal(snapshot.technicalResearchFactory.evidenceAdded, false);
  assert.equal(snapshot.technicalResearchFactory.serviceCoreChanged, false);
  assert.equal(snapshot.technicalResearchFactory.productionChanged, false);
  assert.equal(snapshot.factoryFoundation.contractVersion, 1);
  assert.equal(snapshot.factoryFoundation.classification, "ACCEPT-WITH-RISKS");
  assert.deepEqual(snapshot.factoryFoundation.contracts, ["ResearchTarget", "SourceProspect", "ApplicabilityScope", "GapPlan"]);
  assert.equal(snapshot.factoryFoundation.fixtures.length, 5);
  assert.equal(snapshot.factoryFoundation.serviceCoreFieldCount, 44);
  assert.equal(snapshot.factoryFoundation.tenerePilot.authenticated, false);
  assert.equal(snapshot.factoryFoundation.exactNextTasks.length, 1);
  assert.equal(snapshot.factoryFoundation.evidenceAdded, false);
  assert.equal(snapshot.factoryFoundation.coverageChanged, false);
  assert.equal(snapshot.orchestratorFoundation.schemaVersion, 1);
  assert.equal(snapshot.orchestratorFoundation.foundationContractVersion, 1);
  assert.equal(snapshot.orchestratorFoundation.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.orchestratorFoundation.contracts.length, 7);
  assert.equal(snapshot.orchestratorFoundation.eventTypes.length, 13);
  assert.equal(snapshot.orchestratorFoundation.fixtures.length, 4);
  assert.ok(snapshot.orchestratorFoundation.fixtures.every(item => item.replayVerified));
  assert.equal(snapshot.orchestratorFoundation.serviceCoreFieldCount, 44);
  assert.equal(snapshot.orchestratorFoundation.exactNextTasks.length, 1);
  assert.equal(snapshot.orchestratorFoundation.evidenceAdded, false);
  assert.equal(snapshot.orchestratorFoundation.productionChanged, false);
  assert.equal(snapshot.orchestratorFoundation.tenereAuthenticationExecuted, false);
  assert.equal(snapshot.executionPlanner.schemaVersion, 1);
  assert.equal(snapshot.executionPlanner.foundationContractVersion, 1);
  assert.equal(snapshot.executionPlanner.orchestratorSchemaVersion, 1);
  assert.equal(snapshot.executionPlanner.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.executionPlanner.summary.batchesProduced, 1);
  assert.equal(snapshot.executionPlanner.summary.workItemsProduced, 1);
  assert.deepEqual(snapshot.executionPlanner.summary.decisionCounts, { BLOCKED: 1, DEFERRED: 4, "NOT-NEEDED": 1, PLANNED: 1, REJECTED: 1 });
  assert.equal(snapshot.executionPlanner.fixtureResults["tenere-service"].decision, "BLOCKED");
  assert.equal(snapshot.executionPlanner.serviceCoreFieldCount, 44);
  assert.equal(snapshot.executionPlanner.exactNextTasks.length, 1);
  assert.equal(snapshot.executionPlanner.evidenceAdded, false);
  assert.equal(snapshot.executionPlanner.productionChanged, false);
  assert.equal(snapshot.executionPlanner.tenereAuthenticationExecuted, false);
  assert.equal(snapshot.executionAgent.schemaVersion, 1);
  assert.equal(snapshot.executionAgent.orchestratorSchemaVersion, 1);
  assert.equal(snapshot.executionAgent.adapterSchemaVersion, 1);
  assert.equal(snapshot.executionAgent.classification, "ACCEPT-WITH-RISKS");
  assert.equal(snapshot.executionAgent.adapters.length, 10);
  assert.equal(snapshot.executionAgent.serviceCoreFieldCount, 44);
  assert.equal(snapshot.executionAgent.evidenceAdded, false);
  assert.equal(snapshot.executionAgent.researchedNoEvidenceAdded, false);
  assert.equal(snapshot.executionAgent.productionChanged, false);
  assert.equal(snapshot.executionAgent.tenereAuthenticationExecuted, false);
});

test("project memory has one active roadmap phase and unique ADRs", () => {
  const roadmap = read("docs/project/ROADMAP.md");
  assert.equal((roadmap.match(/\(ACTIVE\)/g) || []).length, 1);
  const decisions = read("docs/project/DECISIONS.md");
  const ids = [...decisions.matchAll(/## (ADR-\d+)/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length);
  const state = read("docs/project/CURRENT_STATE.md");
  assert.equal((state.match(/\*\*NEXT\*\*/g) || []).length, 1);
  assert.match(state, /Technical Research Factory Execution Agent/);
});

test("project memory records production/research isolation", () => {
  assert.match(read("docs/project/README.md"), /Authority order/);
  assert.match(read("docs/project/chat-archive/README.md"), /NON-AUTHORITATIVE HISTORICAL CONTEXT/);
  assert.match(read("docs/project/CURRENT_STATE.md"), /Research is quarantined/);
  assert.doesNotMatch(read("index.html"), /research\/data|research\/lib/);
});

test("audit standard and batch metrics prevent circular acceptance", () => {
  const standard = read("docs/project/AUDIT_STANDARD.md");
  assert.match(standard, /IMPLEMENT → AUTHOR TESTS → INDEPENDENT AUDIT/);
  assert.match(standard, /JUSTIFIED-WITH-RISK/);
  assert.match(standard, /ACCEPT-WITH-RISKS/);
  assert.match(standard, /attempts to falsify/);
  assert.equal(snapshot.research.batchWave2.practicalServiceFieldGain, 0);
  assert.equal(snapshot.research.batchWave2.verifiedBefore, 51);
  assert.equal(snapshot.research.batchWave2.verifiedAfter, 57);
});

test("project memory records the executed pilot and operator cloud note", () => {
  const state = read("docs/project/CURRENT_STATE.md");
  assert.match(state, /\*\*NEXT\*\*/);
  assert.match(read("docs/project/WORKLOG.md"), /high-value source-acquisition/);
  assert.match(state, /101\/220/);
  assert.match(state, /FACTORY-PILOT-CANDIDATE/);
  assert.match(read("docs/project/DECISIONS.md"), /ADR-010/);
  assert.match(read("docs/project/DECISIONS.md"), /ADR-011/);
  assert.match(read("docs/project/DECISIONS.md"), /ADR-013/);
});
